<?php
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link https://github.com/pacificnm/pacificnm-acl-role for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license https://github.com/pacificnm/pacificnm-acl-role/blob/master/LICENSE.md
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate("Application Role"); ?> 
					<small><?php echo $this->entity->getAclRoleName(); ?></small>
				</h3>
				<div class="box-tools">
					<?php echo $this->deleteButton("acl-role-delete", array("id" => $this->entity->getAclRoleId())); ?>
					
					<?php echo $this->updateButton("acl-role-update", array("id" => $this->entity->getAclRoleId())); ?>
				</div>
			</div>
			<div class="box-body box-profile">
				<h3 class="profile-username text-center"></h3>
				<p class="text-muted text-center">
					<?php echo $this->translate('Role ID'); ?> <?php echo $this->entity->getAclRoleId(); ?>
				</p>
				<ul class="list-group list-group-unbordered">
    				<li class="list-group-item">
    					<b><?php echo $this->translate('Role Id'); ?>:</b>
    					<?php echo $this->entity->getAclRoleId(); ?>
    				</li>
    				<li class="list-group-item">
    					<b><?php echo $this->translate('Role Name'); ?>:</b>
    					<?php echo $this->entity->getAclRoleName(); ?>
    				</li>
    			</ul>
    		</div>
    	</div>
    </div>
</div>